<?php
use Roots\WPConfig\Config;
use function Env\env;
/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */
require_once dirname(__DIR__) . '/vendor/autoload.php';

/**
 * Common Settings
 */

Config::define('WP_CACHE_KEY_SALT', env('WP_CACHE_KEY_SALT') ?? 'becagis.vn');
Config::define('WP_REDIS_PORT', env('WP_REDIS_PORT') ?? 6379);
Config::define('WP_REDIS_HOST', env('WP_REDIS_HOST') ?? 'redis');
Config::define('WP_REDIS_PASSWORD', env('WP_REDIS_PASSWORD') ?? 'redis@123');

require_once dirname(__DIR__) . '/config/application.php';

require_once ABSPATH . 'wp-settings.php';
